Create a Fernet key and pass it to relevant containers
CSCfi/airflow-openshift pull request #4
Opened 2020-06-16 07:55 UTC by MWargelin

2020-06-17 09:34 UTC, apurvann requested changes

2020-06-17 09:34 UTC, apurva3000 commented on AirflowTemplate.yml
> +        storage: 1M
1Mi

2020-06-17 10:14 UTC, MWargelin commented on AirflowTemplate.yml
> +        storage: 1M
Thanks, fixed :+1:

2020-06-24 08:47 UTC, apurvann approved these changes

2020-06-24 09:07 UTC, merged